#!/bin/sh

##############################################################################
## Gradle start up script for POSIX generated by Gradle.
##############################################################################

APP_NAME="Gradle"
APP_BASE_NAME=`basename "$0"`
DEFAULT_JVM_OPTS="-Xmx64m -Xms64m"
DIRNAME=`dirname "$0"`
CLASSPATH=$DIRNAME/gradle/wrapper/gradle-wrapper.jar
JAVACMD="${JAVA_HOME:-}/bin/java"
exec "$JAVACMD" $DEFAULT_JVM_OPTS -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
